# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: student.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.empty_pb2
import student_pb2


class StudentServiceBase(abc.ABC):

    @abc.abstractmethod
    async def CreateStudent(self, stream: 'grpclib.server.Stream[student_pb2.Student, student_pb2.Student]') -> None:
        pass

    @abc.abstractmethod
    async def GetStudent(self, stream: 'grpclib.server.Stream[student_pb2.GetStudentRequest, student_pb2.Student]') -> None:
        pass

    @abc.abstractmethod
    async def UpdateStudent(self, stream: 'grpclib.server.Stream[student_pb2.UpdateStudentRequest, student_pb2.Student]') -> None:
        pass

    @abc.abstractmethod
    async def DeleteStudent(self, stream: 'grpclib.server.Stream[student_pb2.DeleteStudentRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def ListStudent(self, stream: 'grpclib.server.Stream[student_pb2.ListStudentsRequest, student_pb2.ListStudentsResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/student.StudentService/CreateStudent': grpclib.const.Handler(
                self.CreateStudent,
                grpclib.const.Cardinality.UNARY_UNARY,
                student_pb2.Student,
                student_pb2.Student,
            ),
            '/student.StudentService/GetStudent': grpclib.const.Handler(
                self.GetStudent,
                grpclib.const.Cardinality.UNARY_UNARY,
                student_pb2.GetStudentRequest,
                student_pb2.Student,
            ),
            '/student.StudentService/UpdateStudent': grpclib.const.Handler(
                self.UpdateStudent,
                grpclib.const.Cardinality.UNARY_UNARY,
                student_pb2.UpdateStudentRequest,
                student_pb2.Student,
            ),
            '/student.StudentService/DeleteStudent': grpclib.const.Handler(
                self.DeleteStudent,
                grpclib.const.Cardinality.UNARY_UNARY,
                student_pb2.DeleteStudentRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/student.StudentService/ListStudent': grpclib.const.Handler(
                self.ListStudent,
                grpclib.const.Cardinality.UNARY_UNARY,
                student_pb2.ListStudentsRequest,
                student_pb2.ListStudentsResponse,
            ),
        }


class StudentServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CreateStudent = grpclib.client.UnaryUnaryMethod(
            channel,
            '/student.StudentService/CreateStudent',
            student_pb2.Student,
            student_pb2.Student,
        )
        self.GetStudent = grpclib.client.UnaryUnaryMethod(
            channel,
            '/student.StudentService/GetStudent',
            student_pb2.GetStudentRequest,
            student_pb2.Student,
        )
        self.UpdateStudent = grpclib.client.UnaryUnaryMethod(
            channel,
            '/student.StudentService/UpdateStudent',
            student_pb2.UpdateStudentRequest,
            student_pb2.Student,
        )
        self.DeleteStudent = grpclib.client.UnaryUnaryMethod(
            channel,
            '/student.StudentService/DeleteStudent',
            student_pb2.DeleteStudentRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.ListStudent = grpclib.client.UnaryUnaryMethod(
            channel,
            '/student.StudentService/ListStudent',
            student_pb2.ListStudentsRequest,
            student_pb2.ListStudentsResponse,
        )
