# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='student.proto',
  package='student',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rstudent.proto\x12\x07student\x1a\x1bgoogle/protobuf/empty.proto\":\n\x07Student\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nstudent_id\x18\x03 \x01(\t\"\'\n\x11GetStudentRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\"J\n\x14UpdateStudentRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x11\n\tnew_value\x18\x03 \x01(\t\"*\n\x14\x44\x65leteStudentRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\":\n\x14ListStudentsResponse\x12\"\n\x08students\x18\x01 \x03(\x0b\x32\x10.student.Student\"\x15\n\x13ListStudentsRequest2\xe1\x02\n\x0eStudentService\x12\x35\n\rCreateStudent\x12\x10.student.Student\x1a\x10.student.Student\"\x00\x12<\n\nGetStudent\x12\x1a.student.GetStudentRequest\x1a\x10.student.Student\"\x00\x12\x42\n\rUpdateStudent\x12\x1d.student.UpdateStudentRequest\x1a\x10.student.Student\"\x00\x12H\n\rDeleteStudent\x12\x1d.student.DeleteStudentRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n\x0bListStudent\x12\x1c.student.ListStudentsRequest\x1a\x1d.student.ListStudentsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_STUDENT = _descriptor.Descriptor(
  name='Student',
  full_name='student.Student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='student.Student.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='student.Student.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='student_id', full_name='student.Student.student_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=113,
)


_GETSTUDENTREQUEST = _descriptor.Descriptor(
  name='GetStudentRequest',
  full_name='student.GetStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='student_id', full_name='student.GetStudentRequest.student_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=154,
)


_UPDATESTUDENTREQUEST = _descriptor.Descriptor(
  name='UpdateStudentRequest',
  full_name='student.UpdateStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='student_id', full_name='student.UpdateStudentRequest.student_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='student.UpdateStudentRequest.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_value', full_name='student.UpdateStudentRequest.new_value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=230,
)


_DELETESTUDENTREQUEST = _descriptor.Descriptor(
  name='DeleteStudentRequest',
  full_name='student.DeleteStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='student_id', full_name='student.DeleteStudentRequest.student_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=274,
)


_LISTSTUDENTSRESPONSE = _descriptor.Descriptor(
  name='ListStudentsResponse',
  full_name='student.ListStudentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='students', full_name='student.ListStudentsResponse.students', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=334,
)


_LISTSTUDENTSREQUEST = _descriptor.Descriptor(
  name='ListStudentsRequest',
  full_name='student.ListStudentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=357,
)

_LISTSTUDENTSRESPONSE.fields_by_name['students'].message_type = _STUDENT
DESCRIPTOR.message_types_by_name['Student'] = _STUDENT
DESCRIPTOR.message_types_by_name['GetStudentRequest'] = _GETSTUDENTREQUEST
DESCRIPTOR.message_types_by_name['UpdateStudentRequest'] = _UPDATESTUDENTREQUEST
DESCRIPTOR.message_types_by_name['DeleteStudentRequest'] = _DELETESTUDENTREQUEST
DESCRIPTOR.message_types_by_name['ListStudentsResponse'] = _LISTSTUDENTSRESPONSE
DESCRIPTOR.message_types_by_name['ListStudentsRequest'] = _LISTSTUDENTSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Student = _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), {
  'DESCRIPTOR' : _STUDENT,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:student.Student)
  })
_sym_db.RegisterMessage(Student)

GetStudentRequest = _reflection.GeneratedProtocolMessageType('GetStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTUDENTREQUEST,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:student.GetStudentRequest)
  })
_sym_db.RegisterMessage(GetStudentRequest)

UpdateStudentRequest = _reflection.GeneratedProtocolMessageType('UpdateStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESTUDENTREQUEST,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:student.UpdateStudentRequest)
  })
_sym_db.RegisterMessage(UpdateStudentRequest)

DeleteStudentRequest = _reflection.GeneratedProtocolMessageType('DeleteStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETESTUDENTREQUEST,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:student.DeleteStudentRequest)
  })
_sym_db.RegisterMessage(DeleteStudentRequest)

ListStudentsResponse = _reflection.GeneratedProtocolMessageType('ListStudentsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTSTUDENTSRESPONSE,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:student.ListStudentsResponse)
  })
_sym_db.RegisterMessage(ListStudentsResponse)

ListStudentsRequest = _reflection.GeneratedProtocolMessageType('ListStudentsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTSTUDENTSREQUEST,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:student.ListStudentsRequest)
  })
_sym_db.RegisterMessage(ListStudentsRequest)



_STUDENTSERVICE = _descriptor.ServiceDescriptor(
  name='StudentService',
  full_name='student.StudentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=360,
  serialized_end=713,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateStudent',
    full_name='student.StudentService.CreateStudent',
    index=0,
    containing_service=None,
    input_type=_STUDENT,
    output_type=_STUDENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStudent',
    full_name='student.StudentService.GetStudent',
    index=1,
    containing_service=None,
    input_type=_GETSTUDENTREQUEST,
    output_type=_STUDENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateStudent',
    full_name='student.StudentService.UpdateStudent',
    index=2,
    containing_service=None,
    input_type=_UPDATESTUDENTREQUEST,
    output_type=_STUDENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteStudent',
    full_name='student.StudentService.DeleteStudent',
    index=3,
    containing_service=None,
    input_type=_DELETESTUDENTREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListStudent',
    full_name='student.StudentService.ListStudent',
    index=4,
    containing_service=None,
    input_type=_LISTSTUDENTSREQUEST,
    output_type=_LISTSTUDENTSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STUDENTSERVICE)

DESCRIPTOR.services_by_name['StudentService'] = _STUDENTSERVICE

# @@protoc_insertion_point(module_scope)
